### ISSUE TITLE
'myfaces' is invalid error

### ISSUE THREAD

**Issue by ZoltanPerhacs** [melloware/wildfly-faces#280]
Tried to run this example project from the command line with the following commands:
_(D:\Temp\wildfly-faces>mvn --version
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: d:\Portable\Development\Tool\apache-maven-3.9.6
Java version: 17.0.10, vendor: Red Hat, Inc., runtime: D:\Portable\Development\Java\java-jdk
Default locale: hu_HU, platform encoding: Cp1250
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

D:\Temp\wildfly-faces>java -version
openjdk version "17.0.10" 2024-01-16 LTS
OpenJDK Runtime Environment (Red_Hat-17.0.10.0+7-2) (build 17.0.10+7-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.10.0+7-2) (build 17.0.10+7-LTS, mixed mode, sharing)
)_

```
D:\Temp>git clone https://github.com/melloware/wildfly-faces
Cloning into 'wildfly-faces'...
remote: Enumerating objects: 3155, done.
remote: Counting objects: 100% (66/66), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 3155 (delta 40), reused 51 (delta 32), pack-reused 3089Receiving objects:  99% (3124/3155), 6.14 MiB | 3.7Receiving objects: 100% (3155/3155), 7.06 MiB | 4.13 MiB/s, done.

Resolving deltas: 100% (2120/2120), done.

D:\Temp>cd wildfly-faces

D:\Temp\wildfly-faces>mvn clean wildfly-jar:dev-watch >out.txt
```

Got the below messages on the console:
```
`WARN: can't find jboss-cli.xml. Using default configuration values.
mßrc. 21, 2024 9:27:12 DE. org.jboss.remoting3.EndpointImpl <clinit>
INFO: JBoss Remoting version 5.0.26.Final
mßrc. 21, 2024 9:27:12 DE. org.xnio.Xnio <clinit>
INFO: XNIO version 3.8.8.Final
mßrc. 21, 2024 9:27:12 DE. org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.8.8.Final
mßrc. 21, 2024 9:27:12 DE. org.wildfly.security.Version <clinit>
INFO: ELY00001: WildFly Elytron version 2.0.0.Final
```

And got the following error int the out.txt:
```
09:27:17,950 INFO  [org.jboss.as.ejb3] (MSC service thread 1-1) WFLYEJB0493: Jakarta Enterprise Beans subsystem suspension complete
09:27:17,980 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0006: Undertow HTTP listener default listening on 127.0.0.1:8080
09:27:18,086 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
09:27:18,093 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
09:27:18,093 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0054: Admin console is not enabled
09:27:18,094 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Preview 28.0.1.Final (WildFly Core 20.0.2.Final) started in 1800ms - Started 217 of 390 services (230 services are lazy, passive or on-demand) - Server configuration file in use: standalone.xml
09:27:18,264 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0027: Starting deployment of "ROOT.war" (runtime-name: "ROOT.war")
09:27:20,807 WARN  [org.jboss.as.jsf] (MSC service thread 1-7) WFLYJSF0005: Unknown Jakarta Server Faces version 'Mojarra-2.0'.  Default version 'myfaces' will be used instead.
09:27:20,808 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-7) MSC000001: Failed to start service jboss.deployment.unit."ROOT.war".DEPENDENCIES: org.jboss.msc.service.StartException in service jboss.deployment.unit."ROOT.war".DEPENDENCIES: WFLYSRV0153: Failed to process phase DEPENDENCIES of deployment "ROOT.war"
	at org.jboss.as.server@20.0.2.Final//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:189)
	at org.jboss.msc@1.5.0.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1590)
	at org.jboss.msc@1.5.0.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1553)
	at org.jboss.msc@1.5.0.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1411)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYJSF0014: Default Jakarta Server Faces implementation slot 'myfaces' is invalid
	at org.jboss.as.jsf@28.0.1.Final//org.jboss.as.jsf.deployment.JSFDependencyProcessor.deploy(JSFDependencyProcessor.java:94)
	at org.jboss.as.server@20.0.2.Final//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:182)
	... 8 more

09:27:20,812 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 1) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "ROOT.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"ROOT.war\".DEPENDENCIES" => "WFLYSRV0153: Failed to process phase DEPENDENCIES of deployment \"ROOT.war\"
    Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYJSF0014: Default Jakarta Server Faces implementation slot 'myfaces' is invalid"}}
09:27:20,812 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 1) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "ROOT.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"ROOT.war\".DEPENDENCIES" => "WFLYSRV0153: Failed to process phase DEPENDENCIES of deployment \"ROOT.war\"
    Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYJSF0014: Default Jakarta Server Faces implementation slot 'myfaces' is invalid"}}
09:27:20,813 ERROR [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0021: Deploy of deployment "ROOT.war" was rolled back with the following failure message: 
{"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"ROOT.war\".DEPENDENCIES" => "WFLYSRV0153: Failed to process phase DEPENDENCIES of deployment \"ROOT.war\"
    Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYJSF0014: Default Jakarta Server Faces implementation slot 'myfaces' is invalid"}}
09:27:20,888 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0028: Stopped deployment ROOT.war (runtime-name: ROOT.war) in 74ms
09:29:26,582 INFO  [org.jboss.as.server] (Thread-2) WFLYSRV0272: Suspending server
09:29:26,586 INFO  [org.jboss.as.ejb3] (Thread-2) WFLYEJB0493: Jakarta Enterprise Beans subsystem suspension complete
09:29:26,587 INFO  [org.jboss.as.server] (Thread-2) WFLYSRV0220: Server shutdown has been requested via an OS signal
09:29:26,600 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0008: Undertow HTTP listener default suspending
09:29:26,600 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0019: Host default-host stopping
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:49 min
[INFO] Finished at: 2024-03-21T09:29:26+01:00
[INFO] ------------------------------------------------------------------------
09:29:26,618 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0007: Undertow HTTP listener default stopped, was bound to 127.0.0.1:8080
09:29:26,621 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0004: Undertow 2.3.6.Final stopping

```

How can i solve this?

**Comment by melloware** [comment]
you are right it looks like Jboss changed something about Galleon packs and I don't have much time to spend on this.

If you really want a standalone bootable JSF app I can recommend Quarkus Faces as its way faster: https://github.com/melloware/quarkus-faces

It builds a totally standalone app that starts in seconds.
